name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -  name: checkout code
    -  uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::123456789012:role/push-to-ecr
        aws-region: us-west-2
        
    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names mentorship-wk2 --region us-weast-2 || \
        aws ecr create-repository --repository-name mentorship-wk2 --region us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myflaskrun:$(date +%s)
    
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v2
      with:
        region: us-west-2
        image: mentorship-wk2:${{ github.sha }}
